name: Comple TeX

on:
  push:
    branches: [ master ]

jobs:
  Test-Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.14.1
          biber-version: 2.17

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-xetex

      - name: Compile Thesis
        working-directory: Thesis
        run: |
          mkdir -p generated
          tectonic --keep-intermediates --reruns 0 -Z shell-escape -Z continue-on-errors thesis_main.tex
          tectonic -Z shell-escape -Z continue-on-errors thesis_main.tex

      - name: Upload Thesis
        uses: actions/upload-artifact@v4
        with:
          name: thesis_main.pdf
          path: Thesis/thesis_main.pdf

      - name: Compile Presentation
        working-directory: Presentation
        run: |
          mkdir -p generated
          tectonic --keep-intermediates --reruns 0 -Z shell-escape -Z continue-on-errors thesis_presentation.tex
          tectonic -Z shell-escape -Z continue-on-errors thesis_presentation.tex

      - name: Upload Presentation
        uses: actions/upload-artifact@v4
        with:
          name: thesis_presentation.pdf
          path: Presentation/thesis_presentation.tex
